spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/order_system
    username: root
    password: 1234 #PasswordEncored.password(password)
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
jwt:
    expiration: 30 #30?
    secretKey: mysecret

#    ??? ?? ?? sql?? ??? ??
